---
- name: Check hostname
  ansible.builtin.command: hostname
  register: current_hostname
  changed_when: false
  tags: hostname

- name: Set computer name
  ansible.builtin.command: scutil --set {{ item }} {{ hostname }}
  with_items:
    - HostName
    - LocalHostName
    - ComputerName
  notify: Flush DNS cache
  become: true
  when: current_hostname.stdout != hostname
  changed_when: current_hostname.stdout != hostname
  tags: hostname

- name: Update NetBIOS name
  community.general.osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ hostname }}"
  tags: hostname
