---
- name: Setting ChallengeResponseAuthentication to false
  become: true
  command: sed -i 's/#\?ChallengeResponseAuthentication \(yes\|no\)/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  tags: ssh

- name: Setting PasswordAuthentication to false
  become: true
  command: sed -i 's/#\?PasswordAuthentication \(yes\|no\)/PasswordAuthentication no/' /etc/ssh/sshd_config
  tags: ssh

- name: Setting UsePAM to false
  become: true
  command: sed -i 's/#\?UsePAM \(yes\|no\)/UsePAM no/' /etc/ssh/sshd_config
  tags: ssh

- name: Restart SSH
  become: true
  command: /etc/init.d/ssh restart
  tags: ssh
