---
- name: Copy private SSH key to hosts
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/
    mode: "preserve"

- name: Copy public SSH key to hosts
  copy:
    src: ~/.ssh/id_rsa.pub
    dest: ~/.ssh/
    mode: "preserve"

- name: Add public SSH key to authorized_keys
  shell: cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
