---
- name: Check for .oh-my-zsh exists
  ansible.builtin.stat:
    path: /{{ (ansible_facts.os_family == 'Darwin')|ternary('Users', 'home') }}/{{ username }}/.oh-my-zsh
  register: ohmyzsh_folder
  tags: oh-my-zsh

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists
  changed_when: true
  tags: oh-my-zsh
