---
- name: Installing zsh package
  become: true
  ansible.builtin.apt:
    name: zsh
    update_cache: yes
  tags: zsh

- name: Setting Zsh as default interpreter
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
  tags: zsh
