---
- name: TextEdit - Configure defaults
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ textedit.defaults }}"
  tags: textedit, defaults
