---
- name: Update and upgrade packages for Homebrew
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags: homebrew, upgrade

- name: Install homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew.taps }}"
  tags: homebrew, taps

- name: Install homebrew formulae
  community.general.homebrew:
    name: "{{ homebrew.formulae }}"
    state: present
  tags: homebrew, formulae

- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew.casks }}"
    state: present
  tags: homebrew, casks
