---
- name: Download and install Containerd
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.6.35/containerd-1.6.35-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  tags: kubernetes

- name: Create Containerd config directory
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
  tags: kubernetes

- name: Get Containerd default configuration
  become: true
  ansible.builtin.shell: containerd config default | tee /etc/containerd/config.toml
  tags: kubernetes

- name: Activate systemd cgroup
  become: true
  ansible.builtin.shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
  tags: kubernetes

- name: Create systemd services directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system
    state: directory
  tags: kubernetes

- name: Download service configuration file
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /etc/systemd/system/containerd.service
  tags: kubernetes

- name: Enabling Containerd service
  become: true
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true
  tags: kubernetes
