---
- name: Make sure apt-transport-https, ca-certificates, curl and gpg are installed
  become: true
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    update_cache: yes
  tags: kubernetes

- name: Adding official Kubernetes GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present
  tags: kubernetes

- name: Adding Kubernetes repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    filename: kubernetes.list
    state: present
  tags: kubernetes

- name: Installing Kubernetes packages
  become: true
  ansible.builtin.apt:
    pkg:
    - kubelet
    - kubeadm
    - kubectl
    update_cache: yes
  tags: kubernetes

- name: Check Kubernetes is active and enabled
  become: true
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: yes
  tags: kubernetes
