---
- name: Prerequisites
  ansible.builtin.include_tasks: prerequisites.yml
  tags: kubernetes

- name: Installing Containerd
  ansible.builtin.include_tasks: containerd.yml
  tags: kubernetes

- name: Installing Runc
  ansible.builtin.include_tasks: runc.yml
  tags: kubernetes

- name: Installing CNI
  ansible.builtin.include_tasks: cni.yml
  tags: kubernetes

- name: Installing Kubernetes
  ansible.builtin.include_tasks: kubernetes_install.yml
  tags: kubernetes

- name: Initializing Kubernetes
  ansible.builtin.include_tasks: kubernetes_init.yml
  tags: kubernetes

- name: Installing Kubernetes addons
  ansible.builtin.include_tasks: kubernetes_addons.yml
  tags: kubernetes

- name: Installing HAProxy
  ansible.builtin.include_tasks: haproxy.yml
  tags: kubernetes
