---
- name: Open iTerm2 to generate default .plist
  ansible.builtin.shell: |
    xattr -dr com.apple.quarantine {{ iterm2_application_path }}
    open -a {{ iterm2_application_path }}
  changed_when: false
  tags: iterm2, plist

- name: Pause to run iTerm2
  ansible.builtin.pause:
    prompt: Press Ctrl+C to quit now if iTerm2 is running
    seconds: 30
  tags: iterm2, plist

- name: Kill iTerm2
  ansible.builtin.shell: |
    killall iTerm2
  changed_when: false
  tags: iterm2, plist

- name: Configure defaults
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ iterm2.defaults }}"
  tags: iterm2, defaults
